### ISSUE TITLE
How do I get the device token?

### ISSUE THREAD

**Issue by nikolas7892** [onmyway133/PushNotifications#1]
Every time I use the device token from either FCM or APNS it returns bad device token. Any detailed steps I can do to solve this?

**Comment by onmyway133** [comment]
@nikolas7892 Hi, this may be a good tutorial https://www.raywenderlich.com/156966/push-notifications-tutorial-getting-started if you haven't read it. Normally, you should get the device token (in form of Data) in this AppDelegate method

`ptional func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data)`
