### ISSUE TITLE
Android: Bad Request 

### ISSUE THREAD

**Issue by semionenko** [onmyway133/PushNotifications#11]
I'm trying to test the push notifications for the android application, but I see Failed: Bad Request. Can I get more information on why this happens? I use the server key and device token as in the description.

**Comment by onmyway133** [comment]
@semionenko Hi, this may solve the problem https://github.com/onmyway133/PushNotifications/pull/14

**Comment by Ariandr** [comment]
Hi @semionenko 
The issue should be fixed in the latest releases. Please, feel free to reopen it if you get the same error.
