### ISSUE TITLE
How to use iOS Provider Certificate iOS Authentication Token Android Server Key

### ISSUE THREAD

**Issue by prohoney** [onmyway133/PushNotifications#13]
No big deal, but when I read the following:

### How to use
---

iOS Provider Certificate
iOS Authentication Token
Android Server Key

I thought the first two are 2 **steps** for iOS. I didn't realize they are two **different** ways of doing it. Clarifying that could reduce ambiguity

**Comment by onmyway133** [comment]
@prohoney yeah, Authentication Token is the NEW way to authenticate with APN server. I should have made this more clearly in the README

**Comment by Ariandr** [comment]
Hi @prohoney 
I clarified the difference between iOS ways in README.
