### ISSUE TITLE
When send IOS fails the spinner does not stop and no error reason given

### ISSUE THREAD

**Issue by saad1200** [onmyway133/PushNotifications#15]
When send IOS fails the spinner does not stop and no error reason given. Probably because the response is undefined at line 154 in InputComponent.js

Thanks for your hard work the application is very useful.

**Comment by SwiftExpert** [comment]
Hey. Happens to me also. how can i fix this? i downloaded the last release but it still happens.

**Comment by mdescalzo** [comment]
I'm seeing this one as well.

**Comment by nareshdb** [comment]
I'm facing this too. Maybe validate your credentials outside of the app resolves this?

**Comment by cefitzger** [comment]
Yeah, I had the typographic issue as well - a comma too many and it just kept going round and round.
Thanks @nareshdb for pointing to the solution.

**Comment by onmyway133** [comment]
Hi all, I will try to spend some time to update some of the dependencies, fix this issue and make new release

**Comment by cefitzger** [comment]
@onmyway133 No problem - I should be better at JSON syntax. Maybe just a warning on the main page would suffice. Thanks

**Comment by L-Yeiser** [comment]
I am also seeing this. JSON syntax is correct. Same payload works for coworker but not me

**Comment by onmyway133** [comment]
@L-Yeiser @cefitzger   Hi, can you post your json here so I can take a look ?

**Comment by cefitzger** [comment]
Hi sorry for the delay. Here's a sample but in fact leaving a comma after the last element causes the problem whatever the content.

```
{
"aps":{
"name" : "Bobby",
"date" : "17:08 on 17/05/19",
"sound" : "default",
"category" : "New game",
}
}
```

**Comment by vikysaran** [comment]
I am still facing same issue.
I used same token, json with another tool and it worked.
I tried with both Auth Key and p12 files, nothing worked. Spinner is moving only.

**Comment by watermamal** [comment]
Its happening to me too, I'm always sending the same thing it worked the 1st 4-5 times and then after that in never stops spinning.

**Comment by preethambaliga** [comment]
Its happening to me too . The spinner never stops.
