### ISSUE TITLE
MacOS Catalina Support

### ISSUE THREAD

**Issue by piers12** [onmyway133/PushNotifications#17]

**Comment by onmyway133** [comment]
@piers12 Hi, thanks for the suggestion. I haven't tried running this on Catalina yet

**Comment by findrails** [comment]
This won't run on Catalina at all, sadly.

<img width="415" alt="Screenshot 2019-07-09 at 11 50 24" src="https://user-images.githubusercontent.com/3594/60882654-3c9c6580-a240-11e9-8885-6cdb6c52a887.png">

I've disabled Gatekeeper, allowed the Mac to run Apps from unidentified sources, but it still won't launch (even with right click - open)

**Comment by yogevbd** [comment]
@piers12 Hi, I Managed to build it on Catalina. All I had to do is to clone the project, `npm install`, `npm run release`, And then use the app built in `PushNotifications-darwin-x64` folder.

**Comment by Amin-Rehman** [comment]
What @yogevbd said unblocked me. thanks a lot!

**Comment by piers12** [comment]
@yogevbd Will give that a try Thanks!

**Comment by saad352** [comment]
If any one can tell me where to find this **PushNotifications-darwin-x64** folder after build.

**Comment by marinbenc** [comment]
@onmyway133 just FYI, you need to notarize the app with Apple for it to be runnable. I'm not sure if you plan on doing that, but there's a good writeup here:

https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

I'd do it but considering you're the owner this repo it makes more sense for you to use your own Apple ID.

**Comment by marinbenc** [comment]
For other people having this issue, if you move the app to your **Applications** folder and **right-click -> Open** you can open the app.

**Comment by onmyway133** [comment]
@marinbenc thanks for the tip, I will do that

**Comment by onmyway133** [comment]
@marinbenc hi, I just uploaded a notarized build https://github.com/onmyway133/PushNotifications/releases/tag/1.7.0, can you help check

Ping @Ariandr

**Comment by Ariandr** [comment]
Hi @onmyway133 
I've read the article. As I understood, `electron-builder` can create unsigned `.dmg` file with signed `.app` inside. 

It says: `Gatekeeper software seems to detect the notarized .app inside the DMG and will let users install your software without problems.`

So, if you notarized the app and shared it as a `.zip`, you should also be able to attach a new `.dmg` file to the build artifacts section.

**Comment by marinbenc** [comment]
@onmyway133 running this on Catalina, it still doesn't seem to open, even though running `spctl --assess --verbose Push\ Notifications.app` shows it as `accepted`.

I don't know much about Electron, but it's possible there's a framework in the project that Gatekeeper doesn't like.

I also noticed the bundle ID in [afterSignHook.js](https://github.com/onmyway133/PushNotifications/blob/2fed712dede8b7a262ebee6418ba8c3fc48cdd87/afterSignHook.js) is different from the one in package.json (it should probably be com.onmyway133.PushNotifications)

Also @Ariandr is correct, right now you can have an unsigned, unnotarized DMG as long as the .app inside is notarized.

However if you sign the DMG it has to be notarized, so make sure it's not signed.

**Comment by onmyway133** [comment]
@Amin-Rehman @marinbenc thanks, I fixed afterSignHook appId and make new build https://github.com/onmyway133/PushNotifications/releases/tag/1.7.0

For some reason, I specified target for mac, but it does not generate dmg, @Ariandr what else should we do?

**Comment by Ariandr** [comment]
@onmyway133 
Try to modify `package.json` scripts section like that.
```
 "scripts": {
    "start": "npx electron main.js",
    "pack": "electron-builder --dir",
    "dist": "electron-builder"
  }
```

And then execute `npm run dist`. 

Also, in targets you might try to specify:
```
"dmg": {
  "sign": false
}
```

It's described here: https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

If nothing helps, I don't know. I personally didn't notarize any apps.

**Comment by Ariandr** [comment]
Also, have you checked the `dist` folder after executing the command? It should contain both `zip` and `dmg`

**Comment by Ariandr** [comment]
@onmyway133 
I've come across this article: https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db

Maybe you've seen it too.

**Comment by onmyway133** [comment]
@Ariandr Hi, I read them, thanks. I checked `dist` folder and there is only `app` file there

**Comment by Ariandr** [comment]
Hi @onmyway133 
I see. If I find any other possible solutions to the problem, I'll let you know.

**Comment by Ariandr** [comment]
@onmyway133 
Maybe if we build with MacOS Catalina, it will work there and it will be enough to just share `app` in `.zip` file.

**Comment by Ariandr** [comment]
I haven't updated any of my devices yet to Catalina, waiting for the official release.

**Comment by onmyway133** [comment]
@Ariandr thanks, I'm waiting for official Catalina too

**Comment by Ariandr** [comment]
Hey guys,
In order to be able to open the app on macOS Catalina you need to install the app using `.dmg` and also follow [this instruction](https://github.com/onmyway133/PushNotifications#opening-app-on-macos-catalina-1015).
Check out the latest release [here](https://github.com/onmyway133/PushNotifications/releases)
