### ISSUE TITLE
Windows File ?

### ISSUE THREAD

**Issue by jassimkm** [onmyway133/PushNotifications#18]
Where is latest windows app 1.4.0

**Comment by Ariandr** [comment]
@jassimkm I will create a build till the end of this week.

**Comment by Ariandr** [comment]
@jassimkm 
I uploaded the .msi file for Windows. Please, check it out.

https://github.com/onmyway133/PushNotifications/releases/tag/1.4.0

**Comment by Ariandr** [comment]
I close the issue, feel free to reopen it if something is wrong with the build. But I tested it, so should be okay.

**Comment by onmyway133** [comment]
@Ariandr Awesome 👍
