### ISSUE TITLE
High Sierra compatibility problem (empty UI)

### ISSUE THREAD

**Issue by Ariandr** [onmyway133/PushNotifications#2]
After downloading the latest release (.zip archive, v.1.1.0) I launched the app. But it is absolutely empty. I suppose it's because I use macOS High Sierra and the app isn't adapted for that OS. Am I wrong? Can it be another issue?
![screen shot 2017-10-12 at 16 30 21](https://user-images.githubusercontent.com/13591333/31498476-b4479462-af6a-11e7-85fb-c7ef05c775d7.png)

**Comment by icyield** [comment]
I can report the same issue too in release 1.1.0. But if I download master it works.

npm install
npm start 

Not tested functionality

**Comment by peterhorsley** [comment]
same issue for me on release 1.1.0 on El Capitan thanks @icyield that works, and i can verify functionality is working.

**Comment by onmyway133** [comment]
@Ariandr @icyield @peterhorsley I just updated to https://github.com/onmyway133/PushNotifications/releases/tag/1.2.0 to make it easier to use. Glad that you find it useful.
