### ISSUE TITLE
Cannot select .p8 token file

### ISSUE THREAD

**Issue by Autospace** [onmyway133/PushNotifications#23]
I have bought and download the app from the App Store
When I select iOS -> Token tab and click on the "SELECT P8" button nothing happens
What's wrong?

OS version: macOS Mojave 10.14.6

**Comment by Ariandr** [comment]
Hi @Autospace 
Please, download the latest version from here in `.dmg` format and install.
https://github.com/onmyway133/PushNotifications/releases/tag/1.6.0

I have the same OS version and the button opens the window to select a file.

**Comment by Autospace** [comment]
Yes, installed newest version of the app from the link you provided resolve the issue.
But the OS talk to me that Developer is not identified and needs more efforts to open the app.
Can you update the app in the AppStore?

**Comment by Ariandr** [comment]
@Autospace 
I've never realized it even existed in the App Store. Can you send a link, please?
Maybe @onmyway133 knows about it.

**Comment by Autospace** [comment]
Sure
https://apps.apple.com/by/app/push-notification-tester/id1475011327?mt=12

Do you want to say that just someone posted an inoperative copy of your application? )))

**Comment by Ariandr** [comment]
@Autospace 
Ah, I see. Probably @onmyway133 added support for deploying the app to the App Store and there is an old version in the Store. I just couldn't find it there myself :)

I believe @onmyway133 will update it to the latest version there and it won't have this issue. So, please consider changing your feedback when it's done.

**Comment by Autospace** [comment]
Ok, thank you very much! :)
