### ISSUE TITLE
Voip Notification issue 

### ISSUE THREAD

**Issue by Muhammedayaz77** [onmyway133/PushNotifications#27]
hi i am facing issue in voip notification "Failed: InvalidPushType". I am working on iOS13 and Xcode 11.
Can you please add push type in UI. Actually  PushType we need to add in header not in payload.

**Comment by Ariandr** [comment]
Hi @Muhammedayaz77 
We set `apns-push-type` header automatically, depending on the payload.
It is set to `alert` in all cases except when `aps` consist of just this (silent notification, aka `background`):
```
"aps" : {
        "content-available" : 1
 }
```

Otherwise, it wouldn't work.

**Comment by Ariandr** [comment]
@Muhammedayaz77 
Can you provide the payload you are sending?

**Comment by Muhammedayaz77** [comment]
hay i am trying to send the Voip notification and for me still it showing "Failed: InvalidPushType" Can you please fix this ASAP. 
if i create a build from Xcode 10 this app works fine. but new i updated my Xcode as Xcode 11 then i start facing this issue. i am not able to send a single voip notification 

payload for Voip :  
{
    "aps" : {
        "alert" : "You got call.",
        "badge" : 9
    }
}


payload for silent notification : 
{
   "aps" :  {
          "content-available" : 1
    }
}

if you need any other details please fill free to mail on my mail id "ayaz.job2010@gmail.com"

**Comment by Ariandr** [comment]
Hi @Muhammedayaz77 
The issue you might not understand is the changes Apple introduced with iOS 13 SDK. Now you cannot use VoIP notifications for old use cases it before. That's why when you build with Xcode 11, you switch to the new SDK and your app doesn't receive such notifications.

There is a great article from OneSignal and there is a section dedicated specifically to this issue, please have a look: [iOS 13 and Xcode 11 Changes That Affect Push Notifications](https://onesignal.com/blog/ios-13-introduces-4-breaking-changes-to-notifications/)

> VoIP Changes
> Apple supports a special type of VoIP (Voice over IP) push permission for some applications. This API was designed for apps that receive voice or video calls, such as Facebook Messenger or Skype.
> 
> Developers found that this special push type also had a few other valuable use-cases, including:
> 
> 1. Applications that were swiped-away from the task switcher could still receive background data notifications. Normally background notifications are ignored if a user closed an app in this method.
> 2. Applications were using this API in order to support receiving encrypted background messages. They would then decrypt the message client side, and then show a local notification.
> 3. Some apps were using this to periodically trigger their app to run code in the background, such as to reliably synchronize data so the user could view it while offline.
> Apple recently changed this permission to require displaying a notification or incoming VoIP call to the user. As a result, VoIP notifications can no longer be used for the three above use-cases, or any other use case that's not related to receiving a VoIP call.
> 
> Instead, Apple recommends implementing many of the above use-cases by using either content-available background notifications, or for the decryption use-case, Apple recommends using a Notification Service Extension. Apple is also introducing a new background tasks framework for cases where apps may need to schedule tasks to happen in the future. These changes, and recommendations on how to handle them, are outlined in Apple's recent WWDC presentation on privacy changes in iOS 13
