### ISSUE TITLE
Stuck when loading

### ISSUE THREAD

**Issue by alexxgarci** [onmyway133/PushNotifications#28]
Hi!

I've a mac OS Mojave 0.14.6. I'm trying to send a notification in iOS with token, it's my first time using this tool but i thing it's all okey. After sending the notification, the loader is stuck and i don't receive the notification.

Thanks in advance.

**Comment by Ariandr** [comment]
Hi @alexxgarci 
Which version of the app are you using?

**Comment by alexgarciaju** [comment]
I download the last version, 1.7.1

**Comment by Ariandr** [comment]
@alexgarciaju  
On Catalina I tested this functionality right now. Doesn't get this issue and notification arrives on my iPhone.
Can you attach a screenshot of stuck loader?

**Comment by alexgarciaju** [comment]
![Screenshot 2019-10-28 at 18 38 23](https://user-images.githubusercontent.com/55234040/67702565-3a5a4480-f9b2-11e9-9901-3fc50ec3aa94.png)

**Comment by Ariandr** [comment]
@alexgarciaju 
It's hard to say what might cause it. Have you tried sending notifications with a simple payload like that?

```
{
    "aps":{
          "alert":"Hello"
    }
}
```

Because if it was a wrong device token, it would tell you so. Maybe the request isn't being sent at all, the issue with the app on your specific macOS version.

**Comment by deepjyot** [comment]
Hi, I'm facing the same issue as mentioned above. I am using the .p12 certificate and on clicking send, the loader gets stuck. I have a Mac OS Mojave 10.14.6 and sending the notification on an iOS 11.1.4 device

**Comment by Ariandr** [comment]
Hi @alexxgarci @deepjyot 
Can you please install v. 1.7.0 and try it? And let us know if it works or not?
It was built on macOS Mojave.

**Comment by Ariandr** [comment]
@deepjyot Thanks for your feedback. At this point I don't have any ideas how we can reproduce this misbehavior.
I will try to update `node-apn` which we use under the hood, maybe it has something to do with the issue.

I will let you know if any fixes are available.

**Comment by romain64** [comment]
Hi, same here. Stuck on loading using .p12 certificate on Mojave 10.14.6. I tried both v1.7.0 and v1.7.1

**Comment by Ariandr** [comment]
Hi @romain64 
I see. It might be specific to this particular version of macOS (Mojave 10.14.6).

**Comment by RusYus** [comment]
Hi, same issue for me. Mojave 10.14.4, v1.7.1. Tried with different internet connections, because for the first time I used proxy, same result, gets stuck on sending. 
P.S. tried on Windows 10, v1.7.1 same thing, so maybe something with `node-apn`?

**Comment by Ariandr** [comment]
Hi @RusYus 
Yes, it's my guess as well, that the issue is with `node-apn`. I tried to switch to the `parse` community fork of that library, but it didn't work.
I will try one more time when I have time.

**Comment by wilsoncampusano** [comment]
The tokens I get from iOS does not have dash, colon or underscore.

**Comment by Ariandr** [comment]
Hi @wilsoncampusano 
Yes, great catch. it might be the issue of the stuck UI.

**Comment by Ariandr** [comment]
Hi @alexgarciaju 
I added validation to checking the iOS device token. On your screenshot you have special characters, which might be the cause of the not responding loader. Even if the issue if different, at least the app will let you know that the device token is incorrect. Check it out here: https://github.com/onmyway133/PushNotifications/releases/tag/1.7.2

**Comment by santoshios** [comment]
I have downloaded the latest release for macOS still facing the same issue, and notification is not getting delivered on device.
Even if I enter wrong device token it still gets stuck at loading does not throw any error

![Screenshot 2019-12-17 at 1 19 16 PM](https://user-images.githubusercontent.com/52994138/70975413-e4f80500-20cf-11ea-84ce-0b6a5f398906.png)

**Comment by wilsoncampusano** [comment]
> I have downloaded the latest release for macOS still facing the same issue, and notification is not getting delivered on device.
> Even if I enter wrong device token it still gets stuck at loading does not throw any error
> 
> ![Screenshot 2019-12-17 at 1 21 57 PM](https://user-images.githubusercontent.com/52994138/70975642-55068b00-20d0-11ea-96a4-f384d62a6595.png)

How do you generate your p12 file ? What steps did you follow ?

**Comment by santoshios** [comment]
> > I have downloaded the latest release for macOS still facing the same issue, and notification is not getting delivered on device.
> > Even if I enter wrong device token it still gets stuck at loading does not throw any error
> > ![Screenshot 2019-12-17 at 1 21 57 PM](https://user-images.githubusercontent.com/52994138/70975642-55068b00-20d0-11ea-96a4-f384d62a6595.png)
> 
> How do you generate your p12 file ? What steps did you follow ?

There is no problem with the p12 file.
I used the same file with nwPusher it worked without issues.
[https://github.com/noodlewerk/NWPusher](url)

**Comment by Ariandr** [comment]
The issue is most definitely with `node-apn`. The library is not maintained as it's for now. The option is the fork, maintained by Parse community `@parse/node-apn`. But it doesn't work with `Electron`. So, for now we cannot fix the issue.

**Comment by mungbeans** [comment]
I set up my iPhone app for push and was able to successfully send pushes to it a few days ago. 
Now I'm using a different Mac and using the same app am unable to send pushes it it - I get the same behaviour as mentioned above. The non working Mac is also Mojave 10.14.6 as somebody else reported. What is node-apn? Some 3rd party library that is being used?  If that is not working then is the app not usable with a Mac from Mojave 10.14.6 onwards? In other words the app just doesn't work if you have a new Mac or updated the OS to the latest?

**Comment by Ariandr** [comment]
Hi @mungbeans 
Yes, `node-apn` is a library used under the hood.
I believe it depends not on the Mac OS version, but on your network connection factors. And in some rare cases the current `node-apn` libarry cannot handle your network requests properly.
For me, the app works on both Mojave and Catalina at work and at home (on different machines).

Also, 99% of users don't have the described issue. You can try to switch to another network.

**Comment by mungbeans** [comment]
> Hi @mungbeans
> Yes, `node-apn` is a library used under the hood.
> I believe it depends not on the Mac OS version, but on your network connection factors. And in some rare cases the current `node-apn` libary cannot handle your network requests properly.
> For me, the app works on both Mojave and Catalina at work and at home (on different machines).
> 
> Also, 99% of users don't have the described issue. You can try to switch to another network.

Hi @Ariandr 
What do you mean by switch to another network? Do you mean a different Wifi/ethernet network I'm using to connect to the internet?

**Comment by Ariandr** [comment]
@mungbeans 
Yes, exactly. I mean a different Internet connection.
I'm not sure it will help, but it's worth a try.
The issue doesn't depend on the Mac OS version.

**Comment by mungbeans** [comment]
I've got two Macs both connected to the same (Wifi) network.
My iMac, which is Mojave 10.14.6, is the one which hangs trying to send the push, my MacBook, which is Mojave 10.14.6 Beta, does not hang.
So its not the internet connection, and unless the Beta is working while the non-beta isn't, which I guess is unlikely, its not the OS version neither.
Are there any experiments you might like me to perform seeing as I have a working and non working Mac simultaneously, that might indicate where the problem might be?

**Comment by Ariandr** [comment]
Hi @mungbeans 
First of all, can you tell me the model of your mac machine on which the app gets stuck? Maybe it has something to do with the internals and the network (WiFi) module which is installed. I think it's unlikely, but if it happens to a small number of users, it might be the case.

Unfortunately, I don't have any particular tests/experiments in mind which can help us understand the problem.

Although, having said that, can you please install this version I attached? it contains updated dependencies and it has `Open dev tools` menu item. It shows the console. Can you please compare the output of consoles between the two machines you have?

https://github.com/onmyway133/PushNotifications/releases/tag/1.8.0-beta
<img width="118" alt="Screenshot at Feb 13 11-45-33" src="https://user-images.githubusercontent.com/13591333/74423321-bc368680-4e58-11ea-8918-1640359fa5b3.png">

**Comment by balkarov** [comment]
I have the same problem on last release version

**Comment by wendaQueue** [comment]
the version of 1.8.0-beta, will crash on macOS 10.15.4

**Comment by caolsen** [comment]
This may be obvious/unrelated, but you might want to check and make sure you haven't deleted or moved your .p12 file.

I was experiencing the same problem and eventually realized that I had deleted the .p12 from my file system. The app does not appear to validate (at least in a way that is visible to the user) that the file still exists. I replaced the .p12 and everything was good again.

**Comment by Ariandr** [comment]
Hi @caolsen 
Great point. Seems legit!
I'll try to add the check to make sure the chosen file exists.

**Comment by robertmryan** [comment]
FWIW, I was getting this "Loading..." message having moved my auth key p8 file. Even when I attached to the p8 in the new location, it persisted with the "Loading..." message. I finally discovered that re-entering all the key id, team id, and device id seemed to have reset something an the "Loading..." message finally went away. In case this helps anyone else...

**Comment by ChechkovEugene** [comment]
I have the same problem on last release version.
Mac os 10.15.6 (19G2021)

Version 1.8.0-beta Thays that it's a malware :  “Push Notifications” will damage your computer. You should move it to the Bin. Report malware to Apple to protect other users

**Comment by uypoko** [comment]
I ran into a similar problem today. The reason is that the p8 file's name wasn't correct. I downloaded the file through Free Download Manager and it got the file's name as "download" so I had to add ".p8" at the end of it. Push Notifications got stuck at loading when I tried to send a notification.

After downloading it with Chrome and got the correct file name. It worked.

**Comment by Ariandr** [comment]
Hi guys

I've solved the issue.
Please, check out a new release:
https://github.com/onmyway133/PushNotifications/releases/tag/1.7.7

Now it will show this error message and won't proceed with the request:
<img width="392" alt="Screenshot at Oct 08 12-36-06" src="https://user-images.githubusercontent.com/13591333/95441509-e2b6ae00-0962-11eb-967b-d0e0e74ce113.png">
