### ISSUE TITLE
Could not receive push notifications in IOS 13 but works in IOS 12

### ISSUE THREAD

**Issue by cnapenas** [onmyway133/PushNotifications#33]
I am not sure if this is a server issue but one thing I've read is that TLS v1 has been already disabled. So just wanted to confirm if this app is still using TLS v1?

Thanks

**Comment by Ariandr** [comment]
Hi @cnapenas 
I suppose `node-apn` (the tool used under the hood) uses TLS v1.2.

Did you use the latest stable version of the app to send push notifications?

The problem with not receiving push notifications on IOS 13 might be connected to many different issues starting from the payload you send.

**Comment by cnapenas** [comment]
Yes, I have already made the necessary changes for the payload. 
{
  "aps": {
    "alert": "Breaking News!",
    "sound": "default",
    "link_url": "https://raywenderlich.com",
"apns-push-type" : "alert",
"content-available" : 1,
"apns-priority" : 5
  }
}

I am using version 1.7.3 which is the latest stable version

**Comment by cnapenas** [comment]
> Hi @cnapenas
> I suppose `node-apn` (the tool used under the hood) uses TLS v1.2.
> 
> Did you use the latest stable version of the app to send push notifications?
> 
> The problem with not receiving push notifications on IOS 13 might be connected to many different issues starting from the payload you send.

Hi @Ariandr 

Yes, I have already made the necessary changes for the payload.
{
"aps": {
"alert": "Breaking News!",
"sound": "default",
"link_url": "https://raywenderlich.com",
"apns-push-type" : "alert",
"content-available" : 1,
"apns-priority" : 5
}
}

I am using version 1.7.3 which is the latest stable version

**Comment by Ariandr** [comment]
@Ariandr 
Your payload is wrong.
The app sets all needed headers (like `apns-priority`, `apns-push-type`)  and in `aps` you can put only predefined params, not custom.
It must look like that:

```
{
"aps": {
    "alert": "Breaking News!",
    "sound": "default",
    "content-available" : 1
},
"link_url": "https://raywenderlich.com"
}
```

**Comment by cnapenas** [comment]
> {
> "aps": {
>     "alert": "Breaking News!",
>     "sound": "default",
>     "content-available" : 1
> },
> "link_url": "https://raywenderlich.com"
> }

I tried that just now and it still is not receiving any notifs

**Comment by cnapenas** [comment]
ok got it now. Thanks! my Bad!
