### ISSUE TITLE
Unable to select a P8 file

### ISSUE THREAD

**Issue by jyoti-k-dev** [onmyway133/PushNotifications#36]
On the latest release 1.7.4, when I try to upload a p8 file for authentication token for ios, the file select dialog opens, but nothing happens when I click on Open. The file is not selected.

**Comment by Ariandr** [comment]
Hi @jyoti-k-dev 
Yes, you are right. It happened because of switching to 8-x version of Electron.

I changed the version to the older one, it seems to work just fine.
Please, check out the release.
https://github.com/onmyway133/PushNotifications/releases/tag/1.7.5

**Comment by netbe** [comment]
@Ariandr  I had the same issue, this resolved it, thks

**Comment by jyoti-k-dev** [comment]
@Ariandr  Thanks for the quick response. it works now

**Comment by Ariandr** [comment]
Hi @jyoti-k-dev 
Okay, great, then I'm closing the issue.
