### ISSUE TITLE
“Push Notifications” will damage your computer. You should move it to the Trash.

### ISSUE THREAD

**Issue by wenhw** [onmyway133/PushNotifications#37]
![image](https://user-images.githubusercontent.com/1060948/79948343-4711ae00-84a6-11ea-93b7-35e70f328bac.png)

**Comment by Ariandr** [comment]
Please, install the latest release, this crash is fixed there.

**Comment by Ariandr** [comment]
Closing the issue, it's a duplicate of https://github.com/onmyway133/PushNotifications/issues/35
