### ISSUE TITLE
Store auth details

### ISSUE THREAD

**Issue by grosch** [onmyway133/PushNotifications#4]
Things like the Auth keypath, team id, key id, etc... are probably never going to change.  Please save those across app launches so I don't have to look them up every time.

**Comment by onmyway133** [comment]
@grosch Hi, sounds like a good idea. I would love to have this ability too. I'm a bit busy at the moment, will try to do at as soon as possible 💪

**Comment by onmyway133** [comment]
@grosch Hi, I just updated project and released 1.3.0 which auto saves settings https://github.com/onmyway133/PushNotifications/releases/tag/1.3.0, can you check that it works for you?

**Comment by grosch** [comment]
Mostly works, thanks!  It's not storing the authentication type so I have to select token each time.

**Comment by onmyway133** [comment]
@grosch Nice, haven't stored the authentication type, will fix that when I have time
