### ISSUE TITLE
getting error 

### ISSUE THREAD

**Issue by pushpankfinoit** [onmyway133/PushNotifications#40]
Push Notifications” can’t be opened because Apple cannot check it for malicious software.

**Comment by Ariandr** [comment]
Hi @pushpankfinoit 
Specifically for that case there is a link pointing to the fix in each single release: https://github.com/onmyway133/PushNotifications#opening-app-on-macos-catalina-1015

<img width="781" alt="Screenshot at Jun 23 13-40-44" src="https://user-images.githubusercontent.com/13591333/85394392-2eca1800-b557-11ea-9fa3-23c2db652c64.png">
