### ISSUE TITLE
Cannot open on macOS 10.15.3

### ISSUE THREAD

**Issue by libern** [onmyway133/PushNotifications#43]
![image](https://user-images.githubusercontent.com/1830640/87217399-4ee14000-c37b-11ea-8b74-71a47c24c9ae.png)

![image](https://user-images.githubusercontent.com/1830640/87217396-47ba3200-c37b-11ea-84bc-01e1605162a0.png)

**Comment by bn326160** [comment]
I have the same on 10.15.5.
The error I get is: “Push Notifications” will damage your computer. You should move it to the Bin.
In the macOS crash logs it tells us that the certificate is invalid.

So I downloaded the master branch and tried to build it and we get: CSSMERR_TP_CERT_REVOKED
But simply starting it using 'npm i && npm start' worked well :)

**Comment by Ariandr** [comment]
Hi @libern @bn326160 
I fixed the issue and created a new release with a fix.
Please, check it out: https://github.com/onmyway133/PushNotifications/releases/tag/1.7.6

**Comment by bn326160** [comment]
Can confirm that it is resolved!

**Comment by Ariandr** [comment]
@bn326160 
Great!

**Comment by libern** [comment]
Double confirm that it is resolved!
