### ISSUE TITLE
MacOS High Sierra. 10.13.3

### ISSUE THREAD

**Issue by mrengine** [onmyway133/PushNotifications#5]
Trying to launch the app, but always get error: Cannot be opened because of problem. 
Full error: http://joxi.net/1A5XozZundZLy2

Using the latest release build (1.2.3)

**Comment by onmyway133** [comment]
@mrengine I think this is an `electron.js` issue. Let me check

**Comment by mrengine** [comment]
@onmyway133  sorry, is there any update?

**Comment by onmyway133** [comment]
@mrengine Hi, sorry for late response, I've been sick for the whole week. I just updated to macOS 10.13.3 and download the release https://github.com/onmyway133/PushNotifications/releases/tag/1.2.3, I can still run and the app works fine

**Comment by mrengine** [comment]
@onmyway133 feel better! have the same error :(

**Comment by onmyway133** [comment]
@mrengine Yeah, then I don't think it is related to `electron.js`. I searched and found people complaining about this problem, for example https://apple.stackexchange.com/questions/225832/apps-cannot-be-opened-because-of-a-problem
