### ISSUE TITLE
I added support for Linux and Windows platforms, want to create a pull request🙂

### ISSUE THREAD

**Issue by Ariandr** [onmyway133/PushNotifications#6]
I made a fork. https://github.com/Ariandr/PushNotifications

Then I updated some dependencies and instead of "electron-packager" I used "electron-builder". I managed to build apps for Linux and Windows with `npm run dist`.
Of course, I built for macOS as well.

For example, that's app for Windows.

![capture](https://user-images.githubusercontent.com/13591333/43202162-5a9f3ec0-9023-11e8-851b-fa92a85dc73a.PNG)

Also, I can share the app installers for Windows(.msi) and Linux(.deb, .AppImage).
So, what do you say?🙂

**Comment by onmyway133** [comment]
@Ariandr hi, this is great. I'm happy to see your PR, we can collaborate on this

**Comment by Ariandr** [comment]
@onmyway133 , great! I will create PR :)

Here is the link to .zip with Windows and Linux versions of the app.
[https://drive.google.com/file/d/1K1og5oMmh79iLEvy1dp2mc8vvfmdCbAX/view?usp=sharing](url)

To build the Mac version, you will just need run `npm run dist` on your mac, which will create a directory with build files and the app.
![screenshot at aug 01 15-29-35](https://user-images.githubusercontent.com/13591333/43521731-c702adb4-959f-11e8-8914-e345442ab2bd.png)
![screenshot at aug 01 15-32-07](https://user-images.githubusercontent.com/13591333/43521838-12ed3622-95a0-11e8-9fd4-757f1a38a3ca.png)

**Comment by Ariandr** [comment]
#7
