### ISSUE TITLE
The app's window after launching the app is blank (1.3.0)

### ISSUE THREAD

**Issue by Ariandr** [onmyway133/PushNotifications#8]
It seems the new release has the old issue. Then I cloned the repository and built it to make sure, got the same problem. I will try to solve it. If I'm successful, I'll let you know.

![screen shot 2018-08-16 at 11 58 01](https://user-images.githubusercontent.com/13591333/44199063-c389b080-a14b-11e8-9e95-283996fe1b53.png)

**Comment by onmyway133** [comment]
@Ariandr Hi, I updated electron and used `npm run dist` of `electron-builder`. Let me research further

**Comment by Ariandr** [comment]
@onmyway133 I'm not sure, but I assume it has something to do with dependencies.

**Comment by Ariandr** [comment]
@onmyway133 Because when I ran `npm install`, the `package-lock.json` got lots of changes, because you added node_modules to .gitignore. It can be a cause.

**Comment by onmyway133** [comment]
@Ariandr Like last time, it runs fine with `npm run start`, but not when release

**Comment by onmyway133** [comment]
@Ariandr Hi, it is because of `apn` being in devDependencies 🙄 , I just updated release https://github.com/onmyway133/PushNotifications/releases/tag/1.3.0, could you have another check ?

**Comment by Ariandr** [comment]
@onmyway133 Yes, sure)

**Comment by Ariandr** [comment]
@onmyway133 Seems to work fine, thanks)))

**Comment by onmyway133** [comment]
@Ariandr 🕺
